### ISSUE TITLE
[要件定義]システム要件定義書

### ISSUE THREAD

**Issue by IotaTech-Info** [IotaTech-Info/certificate-online#13]
ユーザとの打ち合わせ

流れ
⓪事前に説明資料の連携
①システム要件定義書に対して、内容の説明
②ユーザからの質問を回答（★ユーザからの補足）
③指摘より成果物の改修
④改修後に①～③の繰り返す

**Comment by hayleyqinn** [comment]
[team A -  [要件定義]ユーザヒアリング.pptx](https://github.com/IotaTech-Info/certificate-online/files/11195794/team.A.-.pptx)

**Comment by see3rd** [comment]
teamB-スライド：https://docs.google.com/presentation/d/17YahkhiFntjibD8fRGj1SAaVzd8r9S1AXBjO4zczzEs/edit?usp=sharing

**Comment by liuxiaoyang98** [comment]
[team C - [要件定義]ユーザヒアリング.pptx.pptx](https://github.com/IotaTech-Info/certificate-online/files/11196730/team.C.-.pptx.pptx)

**Comment by liuxiaoyang98** [comment]
[team C - [要件定義]ユーザヒアリング.pptx](https://github.com/IotaTech-Info/certificate-online/files/11196734/team.C.-.pptx)

**Comment by liuxiaoyang98** [comment]
[team C - [要件定義]ユーザヒアリング.pptx](https://github.com/IotaTech-Info/certificate-online/files/11196739/team.C.-.pptx)
